name: 🚀 Deploy to Linode

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: checkout
        uses: actions/checkout@v2

      - name: Kubernetes set context
        uses: Azure/k8s-set-context@v1
        with:
          method: kubeconfig
          kubeconfig: ${{ secrets.KUBE_CONFIG }}

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            diddledan/ubuntu-chatlog-mirror:${{ github.sha }}
            diddledan/ubuntu-chatlog-mirror:latest
      
      - uses: azure/k8s-deploy@v1.2
        with:
          namespace: default
          manifests: |
            manifests/deployment.yml
          images: |
            diddledan/ubuntu-chatlog-mirror:${{ github.sha }}
