name: 🚀 Deploy to Production

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
    - uses: actions/checkout@master

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    ## generic k8s
    # - name: Kubernetes set context
    #     uses: Azure/k8s-set-context@v1
    #     with:
    #       method: kubeconfig
    #       kubeconfig: ${{ secrets.KUBE_CONFIG }}

    ## Azure
    - uses: azure/k8s-set-context@v1
      with:
        kubeconfig: ${{ secrets.aks_danik8s_kubeConfig }}
      id: login

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to Docker Hub
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          diddledan/ubuntu-chatlog-mirror:${{ github.sha }}
          diddledan/ubuntu-chatlog-mirror:latest

    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep ubuntu-chatlogs | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
          echo `kubectl create namespace ubuntu-chatlogs`
        fi

    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: ubuntu-chatlogs
        manifests: |
          manifests/deployment.yml
        images: |
          diddledan/ubuntu-chatlog-mirror:${{ github.sha }}
